name: Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel setuptools
    
    - name: Build package
      run: |
        python -m build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-packages
        path: dist/
    
    - name: Build Docker image
      if: contains(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
      run: |
        docker build -t myhandylife/webwaka-agriculture:${{ github.sha }} .
        docker build -t myhandylife/webwaka-agriculture:latest .
    
    - name: Log in to Docker Hub
      if: contains(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image
      if: contains(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
      run: |
        docker push myhandylife/webwaka-agriculture:${{ github.sha }}
        docker push myhandylife/webwaka-agriculture:latest
