name: Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run basic security checks
      run: |
        echo "Running basic security validation..."
        # Check for common security issues
        find . -name "*.py" -exec grep -l "password\|secret\|key" {} \; || true
        find . -name "*.js" -exec grep -l "password\|secret\|key" {} \; || true
        echo "Security check completed"
    
    - name: Dependency Review
      uses: actions/dependency-review-action@v3
      if: github.event_name == 'pull_request'
